---
- hosts: servers
  vars:
  - warName: app.war
  - warRemotePath: /app
  - logFile: /var/log/application.log

  tasks:

  - name: Delete existent war file
    file: path={{ warRemotePath }}/{{ warName }} state=absent

  - name: Download WAR to server
    command: wget ftp://jenkinsaplications.mycompany.com/application.war -O {{ warRemotePath }}/{{ warName }}
 
  - name: Start Application and save output to logfile
    command: java -jar {{ warRemotePath }}/{{ warName }} > {{ logFile }}

