---
- hosts: servers
  vars:
  - warName: app.war
  - warRemotePath: /app
  - logFile: /var/log/application.log

  tasks:

  - name: Delete existent war file
    file: path={{ warRemotePath }}/{{ warName }} state=absent

  - name: Download WAR to server
    command: wget https://dev.segware.com.br/jenkins/job/indicare/lastSuccessfulBuild/artifact/target/indicare-0.0.1-SNAPSHOT.war -O {{ warRemotePath }}/{{ warName }}

  - name: Status of Java Process
    shell: ps -ef |  grep jar | grep -v grep
    register: process_list
    changed_when: false

  - name: Kill "Java" if process running
    command: pkill -f 'java -jar'
    when: "process_list.stdout.find('java -jar') == 1"
 
  - name: Start Application and save output to logfile
    command: /usr/bin/java -jar {{ warRemotePath }}/{{ warName }} > {{ logFile }}

